version: '3'

services:
  saic:
    build:
      context: ./SAIC-Website
      dockerfile: Dockerfile
    # volumes:
    #   - ./SAIC-Website:/usr/share/nginx/html
    ports:
      - '8080:80'
    networks:
      - saic_iit_network

  rails_app:
    build:
      context: ./github-languages
      dockerfile: Dockerfile
    # volumes:
    #   - ./github-languages:/app/data
    ports:
      - '3000:3000'
    networks:
      - rails_app_network

networks:
  saic_iit_network:
  rails_app_network:
